---
title: "Random Feature Selection"
# author: "Mohsen Naghipourfar"
date: "5/28/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Analysis

The following graphs are Density plots for MSE loss of model when K = 2, 4, 8, 16, 32, 64, 128, 256, 512 random features are selected to learn the Encoded Layer from Contractive AutoEncoder. For each model about 50 combination of k features were randomly selected and feed to the model in order to learn the encoded layer of CAE. This resutls are not final. They'll be updated daily.

```{r mohsen, echo=FALSE}
library(readr)
library(ggplot2)
data <- data.frame()
distplot <- function(k) {
  file_name <- paste(c("/Users/Future/Desktop/Spring 2018/Projects/Bioinformatics/Feature Selection/model/Results/CAE/Damavand/encoded_results_0.01_", k, ".csv"), collapse = '')
  plot_title <- paste(c("Distribution Plot (K = ", k, ")"), collapse = '')
  mse_loss <- read_csv(file_name, col_types = cols())
  data <- cbind(data, k = mse_loss)
  data$MSE <- as.numeric(data$MSE)
  # hist(x = data$MSE, breaks = 30, col = 'red', xlab = 'MSE Loss', main = 'Distribution Plot (stddev = 0.01)')
  ggplot(data, aes(MSE)) + geom_density() + xlim(0.25, 0.5)  + xlab("MSE Loss")
}
distplot(2)
distplot(4)
distplot(8)
distplot(16)
distplot(32)
distplot(64)
distplot(128)
distplot(256)
distplot(512)
```

